package mx.edu.utez.uxvibe.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import mx.edu.utez.uxvibe.ConexionBD;

public interface RecordingDao {
  Logger LOGGER = Logger.getLogger(RecordingDao.class.getName());

  String CREATE_TABLE_SQL = "CREATE TABLE GRABACIONES (" +
      "ID_GRABACION NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, " +
      "EMAIL_USUARIO VARCHAR2(255), " +
      "NOMBRE_PRUEBA VARCHAR2(255), " +
      "NOMBRE_PARTICIPANTE VARCHAR2(255), " +
      "TIPO_GRABACION VARCHAR2(50), " +
      "NOMBRE_ARCHIVO VARCHAR2(255), " +
      "AUDIO_DATA CLOB, " +
      "DURACION_SEGUNDOS NUMBER, " +
      "FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP" +
      ")";

  String INSERT_RECORDING_SQL = "INSERT INTO GRABACIONES (EMAIL_USUARIO, NOMBRE_PRUEBA, NOMBRE_PARTICIPANTE, TIPO_GRABACION, NOMBRE_ARCHIVO, AUDIO_DATA, DURACION_SEGUNDOS) "
      +
      "VALUES (?, ?, ?, ?, ?, ?, ?)";

  String SELECT_RECORDING_SQL = "SELECT NOMBRE_ARCHIVO, AUDIO_DATA, DURACION_SEGUNDOS FROM GRABACIONES " +
      "WHERE LOWER(EMAIL_USUARIO)=LOWER(?) AND LOWER(NOMBRE_PRUEBA)=LOWER(?) AND LOWER(NOMBRE_PARTICIPANTE)=LOWER(?) " +
      "ORDER BY ID_GRABACION DESC";

  String DELETE_BY_TEST_SQL = "DELETE FROM GRABACIONES WHERE LOWER(EMAIL_USUARIO)=LOWER(?) AND LOWER(NOMBRE_PRUEBA)=LOWER(?)";

  String DELETE_BY_PARTICIPANT_SQL = "DELETE FROM GRABACIONES WHERE LOWER(EMAIL_USUARIO)=LOWER(?) AND LOWER(NOMBRE_PRUEBA)=LOWER(?) AND LOWER(NOMBRE_PARTICIPANTE)=LOWER(?)";

  Map<String, Map<String, Object>> IN_MEMORY_RECORDINGS = new LinkedHashMap<>();

  default void ensureTableExists() {
    try (
        Connection conn = ConexionBD.getInstancia().getConnection();
        Statement st = conn.createStatement()) {
      st.execute(CREATE_TABLE_SQL);
    } catch (SQLException e) {
      // Table may already exist (ORA-00955: name is already used by an existing
      // object)
    }
  }

  default boolean saveRecording(
      String email,
      String testName,
      String participantName,
      String recordingType,
      String fileName,
      String audioBase64,
      Integer durationSeconds) {
    String normalizedEmail = normalizeEmail(email);
    String normalizedTestName = normalizeText(testName);
    String normalizedParticipant = normalizeText(participantName);
    String key = normalizedEmail + "|" + normalizedTestName + "|" + normalizedParticipant + "|"
        + normalizeText(recordingType);

    Map<String, Object> data = new LinkedHashMap<>();
    data.put("email", normalizedEmail);
    data.put("testName", testName);
    data.put("participantName", participantName);
    data.put("recordingType", recordingType);
    data.put("fileName", fileName);
    data.put("audioData", audioBase64);
    data.put("durationSeconds", durationSeconds);
    IN_MEMORY_RECORDINGS.put(key, data);

    try (
        Connection conn = ConexionBD.getInstancia().getConnection();
        PreparedStatement ps = conn.prepareStatement(INSERT_RECORDING_SQL)) {
      ps.setString(1, normalizedEmail);
      ps.setString(2, testName != null ? testName.trim() : "Prueba");
      ps.setString(3, participantName != null ? participantName.trim() : "Participante");
      ps.setString(4, recordingType != null ? recordingType : "TEST_SESSION");
      ps.setString(5, fileName != null ? fileName : "recording.webm");
      ps.setString(6, audioBase64);
      if (durationSeconds != null) {
        ps.setInt(7, durationSeconds);
      } else {
        ps.setNull(7, java.sql.Types.INTEGER);
      }
      int affected = ps.executeUpdate();
      LOGGER.info("Saved recording to database: affected=" + affected + ", key=" + key);
      return affected > 0;
    } catch (SQLException e) {
      LOGGER.log(Level.WARNING, "Database save recording failed (using memory cache): " + e.getMessage());
      return true;
    }
  }

  default Map<String, Object> getRecording(
      String email,
      String testName,
      String participantName,
      String recordingType) {
    String normalizedEmail = normalizeEmail(email);
    String normalizedTestName = normalizeText(testName);
    String normalizedParticipant = normalizeText(participantName);
    String key = normalizedEmail + "|" + normalizedTestName + "|" + normalizedParticipant + "|"
        + normalizeText(recordingType);

    try (
        Connection conn = ConexionBD.getInstancia().getConnection();
        PreparedStatement ps = conn.prepareStatement(SELECT_RECORDING_SQL)) {
      ps.setString(1, normalizedEmail);
      ps.setString(2, testName != null ? testName.trim() : "");
      ps.setString(3, participantName != null ? participantName.trim() : "");
      try (ResultSet rs = ps.executeQuery()) {
        if (rs.next()) {
          Map<String, Object> result = new LinkedHashMap<>();
          result.put("fileName", rs.getString("NOMBRE_ARCHIVO"));
          result.put("audioData", rs.getString("AUDIO_DATA"));
          result.put("durationSeconds", rs.getInt("DURACION_SEGUNDOS"));
          return result;
        }
      }
    } catch (SQLException e) {
      LOGGER.log(Level.WARNING, "Database get recording failed: " + e.getMessage());
    }

    return IN_MEMORY_RECORDINGS.get(key);
  }

  default boolean deleteByTest(String email, String testName) {
    String normalizedEmail = normalizeEmail(email);
    String normalizedTestName = normalizeText(testName);
    String prefix = normalizedEmail + "|" + normalizedTestName + "|";
    IN_MEMORY_RECORDINGS.keySet().removeIf(k -> k.startsWith(prefix));

    try (
        Connection conn = ConexionBD.getInstancia().getConnection();
        PreparedStatement ps = conn.prepareStatement(DELETE_BY_TEST_SQL)) {
      ps.setString(1, normalizedEmail);
      ps.setString(2, testName != null ? testName.trim() : "");
      ps.executeUpdate();
      return true;
    } catch (SQLException e) {
      LOGGER.log(Level.WARNING, "Database delete recordings by test failed: " + e.getMessage());
      return true;
    }
  }

  default boolean deleteByParticipant(String email, String testName, String participantName) {
    String normalizedEmail = normalizeEmail(email);
    String normalizedTestName = normalizeText(testName);
    String normalizedParticipant = normalizeText(participantName);
    String prefix = normalizedEmail + "|" + normalizedTestName + "|" + normalizedParticipant + "|";
    IN_MEMORY_RECORDINGS.keySet().removeIf(k -> k.startsWith(prefix));

    try (
        Connection conn = ConexionBD.getInstancia().getConnection();
        PreparedStatement ps = conn.prepareStatement(DELETE_BY_PARTICIPANT_SQL)) {
      ps.setString(1, normalizedEmail);
      ps.setString(2, testName != null ? testName.trim() : "");
      ps.setString(3, participantName != null ? participantName.trim() : "");
      ps.executeUpdate();
      return true;
    } catch (SQLException e) {
      LOGGER.log(Level.WARNING, "Database delete recordings by participant failed: " + e.getMessage());
      return true;
    }
  }

  private static String normalizeEmail(String email) {
    return email == null ? "" : email.trim().toLowerCase(Locale.ROOT);
  }

  private static String normalizeText(String text) {
    return text == null ? "" : text.trim().toLowerCase(Locale.ROOT);
  }
}
