-- Password-reset tokens. The app also creates this table on startup if missing.
CREATE TABLE PASSWORD_RESETS (
  TOKEN       VARCHAR2(128) PRIMARY KEY,
  EMAIL       VARCHAR2(150) NOT NULL,
  EXPIRES_AT  TIMESTAMP     NOT NULL,
  USED        NUMBER(1)     DEFAULT 0 NOT NULL
);

CREATE INDEX IDX_PASSWORD_RESETS_EMAIL ON PASSWORD_RESETS (LOWER(EMAIL));
