-- RESPUESTAS aligned with the project schema:
--   ID_RESPUESTA, ID_PRUEBA, ID_PARTICIPANTE, NUMERO_PREGUNTA, RESPUESTA, AUDIO
-- NUMERO_PREGUNTA 0 = audio (filename in RESPUESTA, payload in AUDIO).
-- Other numbers are mapped in QuestionNumbers.java (age, SAM, SUS q1-q15, etc.).
